permissions:
  contents: read
on:
  push:
    branches: [main, master]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  RUST_TOOLCHAIN: nightly-2026-05-12

name: Check
jobs:
  fmt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: fmt
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt
      - run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install ${{ env.RUST_TOOLCHAIN }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-features --all-targets -- -D warnings

  typos:
    runs-on: ubuntu-latest
    name: typos
    permissions:
      contents: read
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - name: Check spelling
        uses: crate-ci/typos@master
